import Head from 'next/head'

import Header from './Header'
import Footer from './Footer'

const Layout = ({title, children}) => {
    return (
        <>
            <Head>
                <title>Espacio Maternitis - {title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
                <main className='contenedor'>
                    {children}
                </main>
            <Footer />
        </>

    )
}

export default Layout